### PR TITLE
chore: add linter configuration

### PR DESCRIPTION
**Pull request by tanya17-05**
## Description
Adding prettier configuration file as mentioned in [issue#38](https://github.com/elixir-cloud-aai/web-components/issues/38)

Fixes #(issue)

- [x] My code follows the [contributing guidelines][contributing] of this
      project, including, in particular, with regard to any style guidelines
- [x] The title of my PR complies with the [Conventional Commits
      specification][conventional-commits]; in particular, it clearly indicates
      that a change is a breaking change
- [x] I am aware that all my commits will be squashed into a single commit,
      using the PR title as the commit message.
- [x] I have performed a self-review of my own code
- [x] I have commented my code in hard-to-understand areas
- [x] I have updated the user-facing documentation to describe any new or
      changed behavior
- [x] I have added type annotations for all function/class/method interfaces
      or updated existing ones
- [x] I have provided [JSDoc][jsdoc] block tags for all
      functions/classes/methods or updated existing ones
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature
      works
- [x] New and existing unit tests pass locally with my changes
- [x] I have not reduced the existing code coverage
- [x] I have asked the [@all-contributors bot][all-contributors-bot] to
      acknowledge my contributions by commenting on this PR with a request of
      the form `@all-contributors please add @YOUR_GH_HANDLE for TYPE_1,
      TYPE_2, ...`, where `TYPE_1` etc. refer to [contribution types supported
      by the All Contributors Specification][all-contributors-types] OR I do
      not want my contributions to be acknowledged

### CODE REVIEW

**Comment by git-anurag-hub** [comment]
Hey @tanya17-05, Thanks for the PR but It will be better if we configure prettier along with the eslint so that they are in sync with each other.

**Comment by uniqueg** [comment]
I agree with @git-anurag-hub. I have added the PR title accordingly (`add lintter configuration`). @git-anurag-hub: can you please give @tanya17-05 some pointer as to how to configure ESLint? And if you have any specific requirements/preferences as for the actual configuration, then please let her know, too. @tanya17-05: you can then just add another commit to your branch and the PR should be updated.

**Comment by git-anurag-hub** [comment]
Sure @uniqueg I talked to @tanya17-05 on slack about this. I think it's better to have some initial code in the repo at first this will give us the idea about many thing which will help us set eslint.

**Comment by uniqueg** [comment]
Yeah, sounds good. But perhaps you could start off with something basic so that we can merge this PR. We can always modify/extend later on

**Comment by git-anurag-hub** [comment]
Yeah, I will init the basic code within next few days.

**Comment by git-anurag-hub** [comment]
Closing this as this is not needed now!

**Pull request closed without merging**
